### ISSUE TITLE
Database crashed after a while

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#100]
This is what `server.sh` had to say:

```
(node:5773) Warning: No such label '29328814-ee19-f587-2945-0b56dfefc0b2: syncFacets' for console.timeEnd()
(node:5773) Warning: No such label '29328814-ee19-f587-2945-0b56dfefc0b2: syncFacets' for console.timeEnd()
(node:5773) Warning: No such label '29328814-ee19-f587-2945-0b56dfefc0b2: syncFacets' for console.timeEnd()
(node:5773) Warning: No such label '29328814-ee19-f587-2945-0b56dfefc0b2: syncFacets' for console.timeEnd()
(node:5773) Warning: No such label '29328814-ee19-f587-2945-0b56dfefc0b2: syncFacets' for console.timeEnd()
(node:5773) Warning: No such label '29328814-ee19-f587-2945-0b56dfefc0b2: syncFacets' for console.timeEnd()
/home/ubuntu/spot/server/spot-server.js:102
    console.time(dataset.dataset.id + ': scanData');
                        ^

TypeError: Cannot read property 'dataset' of undefined
    at Socket.<anonymous> (/home/ubuntu/spot/server/spot-server.js:102:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /home/ubuntu/spot/node_modules/socket.io/lib/socket.js:503:12
```

**Comment by jiskattema** [comment]
Warnings for 'No such label .... syncFacet' have been fixed (removed) in dev branch

If the crash is reproducible, please reopen. We could wrap all server side actions in try/catch to prevent crashes..
