### ISSUE TITLE
Database crash (error included)

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#128]
This was a different error than last time, note that it's still running the old version so you can close if it is fixed in the new one.

```
getDatasets: 7.565ms
            throw new Error("table name must be a string or a builder");
            ^

Error: table name must be a string or a builder
    at _class11._sanitizeTable (/home/ubuntu/spot/node_modules/squel/dist/squel.js:374:19)
    at _class11._table (/home/ubuntu/spot/node_modules/squel/dist/squel.js:1279:22)
    at _class11.from (/home/ubuntu/spot/node_modules/squel/dist/squel.js:1451:14)
    at _class53._this33.(anonymous function) [as from] (/home/ubuntu/spot/node_modules/squel/dist/squel.js:2743:27)
    at Object.getData (/home/ubuntu/spot/server/server-sql-util.js:831:9)
    at /home/ubuntu/spot/server/spot-server.js:133:12
    at Array.forEach (native)
    at child.Collection.(anonymous function) (/home/ubuntu/spot/node_modules/ampersand-collection/ampersand-collection.js:376:36)
    at Socket.<anonymous> (/home/ubuntu/spot/server/spot-server.js:131:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by fdiblen** [comment]
This looks like a problem related to the database server. Have you checked the database server logs?

**Comment by l-hendriks** [comment]
No didn't check. The 'fix' was to restart the database (so just run `serve.sh` again). It looks like something did an invalid query, where the table name was an object or undefined or something.

**Comment by fdiblen** [comment]
It really looks like a Postresql related issue and not SPOT. I suspect your docker container stopped working so SPOT couldnt connect to the database. I suggest you setup a Postgresql server and replace it with docker service.

Closing the issue. Please open it again if necessary.
