### ISSUE TITLE
Not possible to enable two datasets in a session

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#141]
This is currently on idarksurvey.com

```
app.js:43 Uncaught TypeError: Cannot read property 'transform' of undefined
    at http://www.idarksurvey.com/app.js:43:22898
    at Array.forEach (<anonymous>)
    at child.Collection.(anonymous function) (http://www.idarksurvey.com/app.js:1:14542)
    at child.setFacetMinMax (http://www.idarksurvey.com/app.js:43:22762)
    at child.<anonymous> (http://www.idarksurvey.com/app.js:43:20444)
    at Array.forEach (<anonymous>)
    at child.Collection.(anonymous function) (http://www.idarksurvey.com/app.js:1:14542)
    at child.resetDataview (http://www.idarksurvey.com/app.js:43:20290)
    at child.toggleDataset (http://www.idarksurvey.com/app.js:43:22664)
    at http://www.idarksurvey.com/app.js:77:17401
```

**Comment by jiskattema** [comment]
Fixed in current dev branch.
