### ISSUE TITLE
Error: table name must be a string or a builder

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#147]
This error happened on the live environment, crashing the application. I have no further data on this. Is the table name checked before sending to sql? I.e.: can I send an API call with `undefined` as tablename?

```
/home/ubuntu/spot-server/node_modules/squel/dist/squel.js:371
            throw new Error("table name must be a string or a builder");
            ^

Error: table name must be a string or a builder
    at _class11._sanitizeTable (/home/ubuntu/spot-server/node_modules/squel/dist/squel.js:371:19)
    at _class11._table (/home/ubuntu/spot-server/node_modules/squel/dist/squel.js:1265:22)
    at _class11.from (/home/ubuntu/spot-server/node_modules/squel/dist/squel.js:1435:14)
    at _class53._this32.(anonymous function) [as from] (/home/ubuntu/spot-server/node_modules/squel/dist/squel.js:2722:27)
    at Object.getData (/home/ubuntu/spot-server/src/sql-driver.js:931:9)
    at /home/ubuntu/spot-server/src/main.js:104:36
    at Array.forEach (native)
    at child.Collection.(anonymous function) (/home/ubuntu/spot-server/node_modules/ampersand-collection/ampersand-collection.js:376:36)
    at Socket.<anonymous> (/home/ubuntu/spot-server/src/main.js:102:24)
    at emitOne (events.js:96:13)
```

**Comment by fdiblen** [comment]
What version of SPOT is this?
The commit id/branch you are using would help us a lot. Could you also give some information about your database?

**Comment by l-hendriks** [comment]
Sorry I didn't get a notification of the comment. The commit hash is `f9f5b7fa98db96d3c297f85f65dc53f3a296805f`. Probably an old one, I didn't update the codebase in a while as I'm not sure the master branch is 100% stable all the time (maybe release tagging as 0.1.0 would be nice?)

**Comment by fdiblen** [comment]
Could you please try the release 0.1.0 or checkout the master branch?
It would also be easier to debug your problem if you can have a Postresql service running on your system. Please avoid using the old Docker setup.

**Comment by fdiblen** [comment]
any updates on the issue?

**Comment by jiskattema** [comment]
i managed to reproduce the issue; it is related to having no datasets enabled.
The issue is in spot-server; please update to the latest dev version
