### ISSUE TITLE
Refresh doesn't work

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#148]
It generates this error:

```
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/home/ubuntu/spot-server/node_modules/express/lib/response.js:421:11)
    at /home/ubuntu/spot-server/scripts/spot-server.js:103:7
    at Layer.handle [as handle_request] (/home/ubuntu/spot-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/spot-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/spot-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/spot-server/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/spot-server/node_modules/express/lib/router/index.js:281:22
    at param (/home/ubuntu/spot-server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/ubuntu/spot-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/ubuntu/spot-server/node_modules/express/lib/router/index.js:410:3)
```

In the frontend and also in the backend (clogging up the console output)

**Comment by fdiblen** [comment]
Probably related to #147

**Comment by fdiblen** [comment]
solved in dev branch using dev-server
