### ISSUE TITLE
Directly accessing /datasets (e.g., when reloading a apage) and other sub-urls results in an error or 404

### ISSUE THREAD

**Issue by evertrol** [NLeSC/spot#169]
Going directly to the `http://idarksurvey.com/datasets` URL, or reloading the page when in the datasets menu, results in the following error:

```
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/spot-server/node_modules/express/lib/response.js:421:11)
    at /spot-server/scripts/spot-server.js:103:7
    at Layer.handle [as handle_request] (/spot-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/spot-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/spot-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/spot-server/node_modules/express/lib/router/layer.js:95:5)
    at /spot-server/node_modules/express/lib/router/index.js:281:22
    at param (/spot-server/node_modules/express/lib/router/index.js:354:14)
    at param (/spot-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/spot-server/node_modules/express/lib/router/index.js:410:3)
```

OS: macOS 10.13.6
Browsers tried: Chrome, Firefox & Safari

Also on Android with Chrome

Similar for `/analyze` and `/share`.

----

For `http://spot.esciencecenter.nl/datasets` instead, I get a 404. The sub-urls are accessible without a problem from the front page.

**Comment by evertrol** [comment]
Possibly a duplicate of #148

**Comment by fdiblen** [comment]
solved in dev branch using dev-server (also in Docker).
