### ISSUE TITLE
Cannot read property 'isDatetime' of undefined

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#63]
I think you can reproduce this if you rename a facet when it is in a plot

```
Uncaught TypeError: Cannot read property 'isDatetime' of undefined
    at initChart (http://nlesc.github.io/spot/app.js:4:27283)
    at update (http://nlesc.github.io/spot/app.js:4:29075)
    at child.update (http://nlesc.github.io/spot/app.js:5:244)
    at child.<anonymous> (http://nlesc.github.io/spot/app.js:4:17620)
    at Object.triggerEvents (http://nlesc.github.io/spot/app.js:8:14517)
    at child.trigger (http://nlesc.github.io/spot/app.js:8:13138)
    at child.filter.getData (http://nlesc.github.io/spot/app.js:5:19090)
    at http://nlesc.github.io/spot/app.js:5:19495
    at Array.forEach (native)
    at child.Collection.(anonymous function) (http://nlesc.github.io/spot/app.js:8:2713)
```

**Comment by jiskattema** [comment]
Fixed by disabling facet editing for datasets that are in use.
However, the current setup with a dataview that combines datasets needs more explanation / documentation.
