### ISSUE TITLE
Cannot find module intro.js

### ISSUE THREAD

**Issue by bstienen** [NLeSC/spot#89]
When starting the website via the manual on the spot GitHub, I get the error message that the module intro.js could not be found. In the terminal the following error message can be found:

Error: Cannot find module 'intro.js' from '/Users/bstienen/Projects/spot/client/pages'

> spot@0.0.6 css-watch /Users/bstienen/Projects/spot
> stylus -w -o dist --include-css client/stylesheets/app.styl

  watching /Users/bstienen/Projects/spot/node_modules/stylus/lib/functions/index.styl
  watching node_modules/material-design-lite/dist/material.css
  watching node_modules/gridster/dist/jquery.gridster.min.css
Error: client/stylesheets/app.styl:3:9
   1| @import '../../node_modules/material-design-lite/dist/material.css'
   2| @import '../../node_modules/gridster/dist/jquery.gridster.min.css'
   3| @import '../../node_modules/intro.js/minified/introjs.min.css'
--------------^
   4| 
   5| @import 'material_icons.css'
   6| 

failed to locate @import file ../../node_modules/intro.js/minified/introjs.min.css

    at Evaluator.visitImport (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/evaluator.js:915:21)
    at Evaluator.Visitor.visit (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.evaluate (/Users/bstienen/Projects/spot/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/Users/bstienen/Projects/spot/node_modules/stylus/lib/renderer.js:86:26)
    at /Users/bstienen/Projects/spot/node_modules/stylus/bin/stylus:655:15
    at tryToString (fs.js:455:3)
Error: Cannot find module 'intro.js' from '/Users/bstienen/Projects/spot/client/pages'

**Comment by fdiblen** [comment]
Can you please tell me the steps to reproduce the issue?
Installation after a clean check out of master branch seems to be working.

**Comment by bstienen** [comment]
Removing and recloning the entire repository seems to fix this issue :). Thanks for the quick reply.

**Comment by fdiblen** [comment]
No problem :)
